# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=150)),
                ('image_url', models.CharField(max_length=150)),
            ],
        ),
    ]
